name: C++ Build

on:
  push:
    branches:
      - master  # 在推送到 master 分支时触发
  pull_request:
    branches:
      - master  # 在针对 master 分支的拉取请求时触发

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出最新的代码

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2  # 设置 MSYS2 环境
        with:
          update: true  # 更新 MSYS2 到最新版本
          install: >-   # 安装所需的工具
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Add MSYS2 to PATH
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH  # 将 MSYS2 的 bin 目录添加到 PATH

      - name: Compile
        run: g++ -std=c++11 -o Calculator2.0 *.cpp  # 编译所有的 .cpp 文件

