name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出最新的代码

      - name: Set up CMake
        uses: lukka/get-cmake@v3  # 设置 CMake 环境

      - name: Configure with CMake
        run: cmake -S . -B build  # 生成构建系统文件

      - name: Build with CMake
        run: cmake --build build --config Release  # 编译项目
